<a href="https://colab.research.google.com/github/nathan-dinh-dev/tensorflow-deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensor
Step in Machine Learning:
1. Inputs
2. Numerial encoding (change text, or images, or objects into numbers such as tensors)
3. Learns representation (patterns/features/weights)
4. Representation outputs
5. Output

In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimentsions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix.ndim

2

In [7]:
What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

SyntaxError: unterminated string literal (detected at line 1) (ipython-input-7-1938358898.py, line 1)

### Create tensors with tf.Variable

In [8]:
# Create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [9]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [10]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Note: Use tf.constant first then if needed to

In [11]:
# Create a random tensor
random_tensor = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_tensor = random_tensor.normal(shape=(3, 2)) # normal distribution
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent

In [12]:
not_shuffle = tf.constant([[10,7],
                           [3, 4],
                           [2,2]])
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  2]], dtype=int32)>

In [13]:
tf.random.shuffle(not_shuffle)
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  2]], dtype=int32)>

### Create a tensor with Numpy
The main diff between NumPy arrays and Tensorflow tensor is that tensors can be run on a GPU

In [14]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>